version: '3.8'

services:
  webapp:
    image: nginx:alpine
    volumes:
      - .:/var/www/app:cached
      - ./docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:8085"
    depends_on:
      - app
      - database

  app:
    build:
      context: .
      dockerfile: docker/dev/php/Dockerfile
      args:
        PUID: ${PUID}
        PGID: ${PGID}
    depends_on:
      - database
    volumes:
      - .:/var/www/app:cached

  database:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      # seeding scripts
      - ./docker/dev/mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - mongodb:/data/db
      - mongoconfig:/data/configdb

volumes:
  mongodb:
  mongoconfig:
